"""Factual Q&A entries for /knowledge/ — one intent per page."""

from __future__ import annotations

# (slug, category, question, answer, related_guide_slug)
KNOWLEDGE_QA: list[tuple[str, str, str, str, str]] = [
    # --- Healing & aftercare ---
    (
        "tattoo-healing-peeling-las-vegas",
        "Healing & aftercare",
        "Is tattoo peeling normal during healing in Las Vegas?",
        "Light peeling around days 5–14 is normal. In dry Vegas heat, use a thin layer of fragrance-free moisturizer and do not pick flakes — pulling skin can remove ink. See a clinician if peeling comes with spreading redness, pus, or fever.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-healing-itching-desert-climate",
        "Healing & aftercare",
        "Why does my tattoo itch while healing?",
        "Itching usually means the skin barrier is repairing. Pat the area lightly; do not scratch. Low humidity in Las Vegas dries skin faster — stay moisturized and out of direct sun. Rash, welts, or itching that worsens after a week may need medical review.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-infection-signs-when-to-see-doctor",
        "Healing & aftercare",
        "How do I know if my tattoo is infected?",
        "Warning signs include spreading redness beyond the outline, warmth, pus, red streaks, fever, or pain that increases after day 3. Minor irritation is common; infection needs prompt medical care. Contact your artist so they can document healing and adjust aftercare.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-scabbing-normal-or-problem",
        "Healing & aftercare",
        "Is scabbing on a new tattoo normal?",
        "Thin scabbing can happen, especially on dense black work. Do not pick or soak scabs. Heavy, thick scabs often mean the skin was overworked or aftercare was too dry — light moisturizer and artist follow-up help. Picking scabs causes patchy healing.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-second-skin-saniderm-how-long",
        "Healing & aftercare",
        "How long should I keep second skin (Saniderm) on a tattoo?",
        "Follow your artist's instructions — often 24–72 hours for the first piece, then a gentle wash and optional second application. Remove sooner if fluid pools, edges peel with contamination risk, or you see irritation. Never reapply over unwashed skin.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "how-often-wash-new-tattoo",
        "Healing & aftercare",
        "How often should I wash a new tattoo?",
        "Gently wash 2–3 times daily with lukewarm water and fragrance-free soap. Pat dry with a clean paper towel — no rubbing. Over-washing strips healing plasma; under-washing allows bacteria buildup.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "best-soap-for-tattoo-aftercare",
        "Healing & aftercare",
        "What soap is safe for washing a new tattoo?",
        "Use mild, fragrance-free, antibacterial liquid soap without exfoliants or dyes. Harsh bar soaps, alcohol, and scented body wash can irritate open skin. Rinse completely and pat dry.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-aftercare-lotion-vs-ointment",
        "Healing & aftercare",
        "Should I use lotion or ointment on a healing tattoo?",
        "First 48–72 hours: thin ointment only if your artist recommends it. After initial sealing, switch to a thin fragrance-free lotion. Thick layers trap bacteria and cause maceration (soggy skin). Less is more in desert climates.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "sleeping-with-new-tattoo-tips",
        "Healing & aftercare",
        "How should I sleep with a new tattoo?",
        "Wear loose, clean cotton clothing. Avoid sleeping directly on the tattoo when possible — pressure and sweat irritate fresh work. Change sheets if they are not clean; bacteria from fabric is a common healing setback.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-sunscreen-after-healing-las-vegas",
        "Healing & aftercare",
        "When can I use sunscreen on a healed tattoo in Las Vegas?",
        "Wait until all flaking has stopped and the skin feels smooth — typically 3–4 weeks. Then use broad-spectrum SPF 30+ on exposed tattoos daily. UV is intense in Nevada and fades color and grey tones faster than shaded skin.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-swimming-after-getting-inked",
        "Healing & aftercare",
        "How long before I can swim after a tattoo?",
        "Avoid pools, hot tubs, lakes, and ocean until the outer layer has fully closed — usually at least 3–4 weeks. Soaking softens healing skin, introduces bacteria, and can pull ink out of the dermis.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-gym-workout-aftercare",
        "Healing & aftercare",
        "When can I exercise after getting a tattoo?",
        "Light activity is usually fine after 48–72 hours if the area is not rubbed or soaked in sweat. Avoid heavy friction, compression, and contact sports on the tattooed zone until healed. Shower and pat dry after sweating.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-flying-after-session",
        "Healing & aftercare",
        "Can I fly after getting a tattoo?",
        "Yes, once acute oozing has stopped (typically 24–48 hours). Cabin air is dry — bring travel aftercare, avoid tight straps on fresh work, and stay hydrated. Long flights increase swelling on lower-body placements.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-mri-with-ink",
        "Healing & aftercare",
        "Are tattoos safe for MRI scans?",
        "Most modern tattoos are MRI-safe. Rarely, older or metallic pigments may warm slightly during imaging — inform the technician about large or old work. Professional studios use inks formulated for long-term stability in skin.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-aging-and-fading-over-time",
        "Healing & aftercare",
        "Do tattoos fade as you age?",
        "All tattoos soften slightly as skin ages and sees sun. Black and grey holds contrast well when protected with SPF; color needs more touch-ups. Placement on high-friction areas (hands, inner biceps) fades faster than upper back or thigh.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-touch-up-timing",
        "Healing & aftercare",
        "When is the right time for a tattoo touch-up?",
        "Wait until the tattoo is fully healed — at least 6–8 weeks. Fine lines and color often settle lighter after first heal; a touch-up restores contrast once skin has stabilized. Touch-ups are not free fixes for poor aftercare or sun damage.",
        "how_much_do_tattoos_cost_in_las_vegas_authority_guide",
    ),
    # --- Pain & placement ---
    (
        "most-painful-tattoo-placements",
        "Pain & placement",
        "What are the most painful places to get a tattoo?",
        "Ribs, spine, sternum, inner biceps, ankles, feet, and armpits are commonly rated highest. Pain is subjective — fatigue, hydration, and session length matter as much as placement. Our pain chart guide maps sensitivity by body zone.",
        "tattoo_pain_chart_placement_sensitivity_guide",
    ),
    (
        "least-painful-tattoo-placements",
        "Pain & placement",
        "What are the least painful tattoo placements?",
        "Outer upper arm, outer thigh, calf, and shoulder often feel milder because of muscle and fat padding. Avoid booking a large first tattoo on a high-sensitivity zone — build tolerance with smaller work first.",
        "tattoo_pain_chart_placement_sensitivity_guide",
    ),
    (
        "tattoo-on-ribs-recovery",
        "Pain & placement",
        "How painful are rib tattoos and how long do they take to heal?",
        "Rib tattoos are often sharp and deep because skin is thin over bone. Healing timeline matches other areas (2–4 weeks surface heal), but movement from breathing can make the first week uncomfortable. Plan shorter first sessions.",
        "tattoo_pain_chart_placement_sensitivity_guide",
    ),
    (
        "fine-line-tattoo-pain-level",
        "Pain & placement",
        "Do fine line tattoos hurt less?",
        "Fine line often uses lighter passes, which can feel less intense than heavy shading — but session time and placement matter more than style. Fine lines need steady hands and healed clarity; choose an artist with a fine-line portfolio.",
        "fine_line_tattoos_las_vegas_master_authority_guide",
    ),
    # --- Pricing & booking ---
    (
        "how-much-does-tattoo-cost-las-vegas",
        "Pricing & booking",
        "How much do tattoos cost in Las Vegas?",
        "Shop minimums often start around $100–$200; hourly rates for experienced artists commonly run $150–$250+ depending on size, style, and session length. Large realism and cover-ups are quoted after consult — not over the phone.",
        "how_much_do_tattoos_cost_in_las_vegas_authority_guide",
    ),
    (
        "tattoo-shop-minimum-explained",
        "Pricing & booking",
        "What is a tattoo shop minimum?",
        "A minimum covers setup, sterile materials, and artist time for small work — even a tiny symbol. It ensures quality regardless of size. Ask what is included (consult, touch-up window, aftercare) when comparing shops.",
        "how_much_do_tattoos_cost_in_las_vegas_authority_guide",
    ),
    (
        "tattoo-deposit-policy-why-required",
        "Pricing & booking",
        "Why do tattoo shops require a deposit?",
        "Deposits hold your appointment slot and compensate for drawing time. They are usually applied to the session but may be forfeited for no-shows or late cancellations — policies vary; read yours before paying.",
        "how_much_do_tattoos_cost_in_las_vegas_authority_guide",
    ),
    (
        "tattoo-consultation-what-to-bring",
        "Pricing & booking",
        "What should I bring to a tattoo consultation?",
        "Reference images, placement ideas, approximate size, budget range, and any medical notes (blood thinners, skin conditions). Honest about prior tattoos in the same area helps the artist plan cover-ups or adjacent work.",
        "how_to_choose_a_tattoo_artist_master_selection_guide_2",
    ),
    (
        "tattoo-tipping-las-vegas",
        "Pricing & booking",
        "How much should I tip a tattoo artist in Las Vegas?",
        "15–25% of the session total is customary when you are satisfied with the experience. Long realism, cover-ups, and multi-hour sessions reflect significant skill and focus — tips go to the artist who tattooed you.",
        "how_much_do_tattoos_cost_in_las_vegas_authority_guide",
    ),
    (
        "walk-in-tattoo-vs-appointment",
        "Pricing & booking",
        "Should I walk in or book an appointment for a tattoo?",
        "Walk-ins work for small, simple designs when an artist is available. Custom realism, sleeves, and cover-ups require consults and scheduled time. Calling ahead saves disappointment on busy Vegas weekends.",
        "walk_in_tattoos_las_vegas_authority_guide",
    ),
    (
        "how-long-tattoo-session-last",
        "Pricing & booking",
        "How long does a tattoo session usually last?",
        "Small pieces: 1–2 hours. Medium work: 2–4 hours. Large sessions often cap at 4–6 hours for client and artist stamina. Multi-session sleeves are planned in advance with healing gaps between sittings.",
        "how_much_do_tattoos_cost_in_las_vegas_authority_guide",
    ),
    # --- Styles & planning ---
    (
        "black-and-grey-realism-explained",
        "Styles & planning",
        "What is black and grey realism tattooing?",
        "Black and grey realism uses smooth shading and contrast to mimic photographs — portraits, statues, nature, and symbolic imagery. It relies on healed value range, not color. Portfolio proof of healed work matters more than fresh photos.",
        "realism_tattoos_las_vegas_master_authority_guide",
    ),
    (
        "fine-line-tattoo-longevity",
        "Styles & planning",
        "Do fine line tattoos last?",
        "Fine lines heal thinner than bold traditional work — they can blur slightly over years, especially on hands and feet. An experienced fine-line artist adjusts line weight for placement and long-term readability.",
        "fine_line_tattoos_las_vegas_master_authority_guide",
    ),
    (
        "sleeve-tattoo-how-many-sessions",
        "Styles & planning",
        "How many sessions does a full sleeve tattoo take?",
        "Most full sleeves need 3–8+ sessions depending on style, coverage, and pain tolerance. Black and grey realism often requires more hours than bold traditional. Plan months between sessions for healing.",
        "best_tattoo_styles_for_sleeves_large_scale_project_hub",
    ),
    (
        "tattoo-style-matching-artist",
        "Styles & planning",
        "How do I match a tattoo style to the right artist?",
        "Study healed portfolio photos in the style you want — not just fresh ink. Realism, fine line, and traditional require different specialties. A consult confirms whether your reference fits the artist's strengths.",
        "how_to_choose_a_tattoo_artist_master_selection_guide_2",
    ),
    (
        "first-tattoo-tips-before-you-book",
        "Styles & planning",
        "What should I know before my first tattoo?",
        "Eat a meal, hydrate, sleep well, and wear comfortable clothing. Avoid alcohol 24 hours before. Bring ID if you appear under 18 — Nevada requires valid ID proving 18+. Ask questions during the consult; good artists welcome them.",
        "how_to_choose_a_tattoo_artist_master_selection_guide_2",
    ),
    # --- Cover-ups ---
    (
        "tattoo-cover-up-laser-first",
        "Cover-ups",
        "Do I need laser removal before a cover-up tattoo?",
        "Not always. Dense black old ink sometimes needs laser lightening first; many pieces can be redesigned in one or two sessions if size and contrast allow. A cover-up consult maps what is realistically achievable on your skin.",
        "cover_up_tattoos_las_vegas_master_authority_guide",
    ),
    (
        "how-dark-can-cover-up-tattoo-be",
        "Cover-ups",
        "How dark can a cover-up tattoo be compared to the old tattoo?",
        "New design must be larger and often darker or more complex than the original to hide old ink. Exact color matching old tattoos is difficult — expect a new composition, not a patch.",
        "cover_up_tattoos_las_vegas_master_authority_guide",
    ),
    (
        "cover-up-tattoo-consultation-what-happens",
        "Cover-ups",
        "What happens at a cover-up tattoo consultation?",
        "The artist evaluates old ink color, line depth, scarring, and placement. You discuss size, style, and session count. Photos of healed cover-ups in similar situations help set realistic expectations before booking.",
        "cover_up_tattoos_las_vegas_master_authority_guide",
    ),
    # --- Piercing ---
    (
        "piercing-starter-jewelry-fit",
        "Piercing",
        "How does Work of Art choose starter jewelry for a piercing?",
        "Katelyn Cole selects starter jewelry by anatomy, swelling room, placement, and metal-sensitivity history. Specific material and brand claims should be confirmed with the studio during booking.",
        "best_piercing_shop_las_vegas_updated_jewelry_standards",
    ),
    (
        "how-long-piercing-heals",
        "Piercing",
        "How long do ear piercings take to heal?",
        "Lobe: often 6–8 weeks for basic healing. Cartilage (helix, conch, tragus): commonly 6–12 months. Healing varies by anatomy, aftercare, and sleep habits. Do not change jewelry early without piercer approval.",
        "best_piercing_shop_las_vegas_updated_jewelry_standards",
    ),
    (
        "piercing-bump-vs-infection",
        "Piercing",
        "Is a bump on my piercing an infection or irritation?",
        "Irritation bumps often come from snagging, sleeping on the jewelry, or harsh aftercare. Infection adds spreading redness, warmth, pus, and fever. See your piercer first for bumps; see a clinician for infection signs.",
        "best_piercing_shop_las_vegas_updated_jewelry_standards",
    ),
    (
        "can-you-swim-after-ear-piercing",
        "Piercing",
        "When can I swim after a new ear piercing?",
        "Avoid submerging fresh piercings in pools, hot tubs, and lakes for at least 4–6 weeks — longer for cartilage. Bacteria in water is a leading cause of irritation and infection.",
        "best_piercing_shop_las_vegas_updated_jewelry_standards",
    ),
    (
        "ear-curation-multiple-piercings-planning",
        "Piercing",
        "What is ear curation and how are multiple piercings planned?",
        "Ear curation maps jewelry scale, metal, and placement so multiple piercings heal in balance — not all at once. A piercer plans order of work and downsizing timelines for long-term symmetry.",
        "best_piercing_shop_las_vegas_updated_jewelry_standards",
    ),
    # --- Studio choice & Las Vegas ---
    (
        "luxury-studio-vs-strip-walk-in",
        "Choosing a studio",
        "How is a premium tattoo studio different from a Strip walk-in shop?",
        "Premium studios prioritize consults, sterile setup, artist continuity, and healed portfolio proof. Walk-in booths optimize speed and tourist volume. Compare hygiene protocols and revision policies — not just price or proximity to the Strip.",
        "vegas_tattoo_shop_vs_cheap_strip_tattoo_ultimate_comparison",
    ),
    (
        "how-to-compare-tattoo-studios",
        "Choosing a studio",
        "How should I compare tattoo studios in Las Vegas?",
        "Check: autoclave/spore testing, single-use needles, healed portfolio in your style, clear deposit policy, licensed artists, and verifiable reviews. Visit the shop — cleanliness and transparency are visible before you book.",
        "how_to_choose_a_tattoo_artist_master_selection_guide_2",
    ),
    (
        "tattoo-shop-near-strip-worth-drive",
        "Choosing a studio",
        "Is it worth leaving the Strip for a tattoo in Las Vegas?",
        "Strip booths cater to impulse tourists; off-Strip studios like Work of Art on E. Tropicana focus on custom work and repeat clients. A short rideshare often means better consult time and healed-quality portfolios.",
        "tattoo_shop_near_the_strip_nap_corrected",
    ),
    (
        "vegas-tattoo-aftercare-desert-climate",
        "Choosing a studio",
        "Why is tattoo aftercare different in Las Vegas desert climate?",
        "Low humidity and high UV dry skin faster and fade ink sooner. Drink water, use thin moisturizer, avoid sun, and follow artist instructions — generic advice from humid climates often fails in Nevada.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    # --- Myths & facts ---
    (
        "tattoo-and-blood-donation-wait",
        "Myths & facts",
        "How long after a tattoo must I wait to donate blood?",
        "In the U.S., many blood centers require a 3-month deferral after a tattoo if it was done at an unregulated facility. Licensed professional studios in regulated states may have no deferral — confirm with your local blood bank.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "can-you-get-tattoo-while-breastfeeding",
        "Myths & facts",
        "Is it safe to get a tattoo while breastfeeding?",
        "Medical guidance generally recommends waiting — infection risk, medications, and healing stress affect you and the infant. Discuss timing with your doctor and artist; most studios will ask you to wait until you are cleared.",
        "tattoo_healing_in_desert_climate_expert_aftercare_guide",
    ),
    (
        "tattoo-over-scar-tissue",
        "Myths & facts",
        "Can you tattoo over scar tissue?",
        "Often yes, but scar type matters — raised keloid scars may not hold ink well. A consult assesses texture, color, and whether camouflage or decorative work is realistic. Healed scars tattoo better than fresh ones.",
        "cover_up_tattoos_las_vegas_master_authority_guide",
    ),
    (
        "white-ink-tattoo-facts",
        "Myths & facts",
        "Do white ink tattoos stay visible?",
        "White ink alone often fades to a subtle scar-like tone and yellows with sun. It works best as highlight within color or black and grey — not as a standalone \"invisible\" tattoo. Set expectations before booking.",
        "fine_line_tattoos_las_vegas_master_authority_guide",
    ),
    (
        "tattoo-etiquette-studio-behavior",
        "Myths & facts",
        "What is proper etiquette at a tattoo studio?",
        "Arrive on time, fed, and sober. Limit guests, keep phones on silent, and trust the artist's placement advice. Do not compare shops loudly or haggle after a quote — consults are professional appointments.",
        "how_to_choose_a_tattoo_artist_master_selection_guide_2",
    ),
]

# Category display order on hub
KNOWLEDGE_CATEGORIES: tuple[str, ...] = (
    "Healing & aftercare",
    "Pain & placement",
    "Pricing & booking",
    "Styles & planning",
    "Cover-ups",
    "Piercing",
    "Choosing a studio",
    "Myths & facts",
)
