"""Canonical URLs and retire/301 rules for overlapping content."""

from __future__ import annotations

# Legacy slug -> canonical public path (301 on deploy)
CONSOLIDATION_REDIRECTS: tuple[tuple[str, str], ...] = (
    ("tattoo_shop_near_the_strip_geo_seo_optimized", "/tattoo_shop_near_the_strip_nap_corrected/"),
    ("how_to_choose_a_tattoo_artist_master_selection_guide", "/how_to_choose_a_tattoo_artist_master_selection_guide_2/"),
    ("walk_in_tattoos_las_vegas_nap_corrected", "/walk-in-tattoos-las-vegas/"),
    ("healing_database_black_grey_day_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_day_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_day_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_day_4_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_month_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_month_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_month_6_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_tattoos_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_week_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_week_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_week_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_black_grey_year_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_day_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_day_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_day_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_day_4_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_month_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_month_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_month_6_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_tattoos_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_week_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_week_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_week_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_color_year_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_day_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_day_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_day_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_day_4_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_month_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_month_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_month_6_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_tattoos_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_week_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_week_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_week_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_cover_ups_year_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_day_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_day_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_day_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_day_4_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_month_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_month_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_month_6_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_tattoos_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_week_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_week_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_week_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_fine_line_year_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_day_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_day_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_day_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_day_4_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_month_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_month_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_month_6_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_tattoos_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_week_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_week_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_week_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_neo_traditional_year_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_day_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_day_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_day_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_day_4_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_month_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_month_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_month_6_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_tattoos_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_week_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_week_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_week_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_portraits_year_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_day_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_day_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_day_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_day_4_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_month_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_month_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_month_6_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_timeline_encyclopedia_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_week_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_week_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_week_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_tattoo_year_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_day_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_day_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_day_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_day_4_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_month_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_month_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_month_6_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_tattoos_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_week_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_week_2_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_week_3_las_vegas", "/las-vegas-tattoo-healing-guide/"),
    ("healing_database_traditional_year_1_las_vegas", "/las-vegas-tattoo-healing-guide/"),
)

RETIRE_OVERLAP_SLUGS: frozenset[str] = frozenset(
    src for src, _dest in CONSOLIDATION_REDIRECTS
)

CANONICAL_STRIP_DIRECTIONS = "/tattoo_shop_near_the_strip_nap_corrected/"
CANONICAL_OFFICIAL_NAP = "/official_location_hours_contact/"

# Sitewide href replacements (old path fragment -> canonical)
HREF_REPLACEMENTS: tuple[tuple[str, str], ...] = tuple(
    (f"/{src}/", dest) for src, dest in CONSOLIDATION_REDIRECTS
)
