/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./code.html", "../artists_build/joshua-cole.html"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#5f5e5e",
        "on-primary-fixed-variant": "#474646",
        "surface-tint": "#c9c6c5",
        "on-tertiary": "#690000",
        "on-secondary-fixed-variant": "#574500",
        "on-primary": "#313030",
        "secondary-container": "#af8d11",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c4c7c7",
        "primary-fixed": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "secondary-fixed": "#ffe088",
        "inverse-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "on-primary-container": "#7c7a7a",
        background: "#131313",
        "tertiary-fixed": "#ffdad4",
        "on-primary-fixed": "#1c1b1b",
        "on-secondary": "#3c2f00",
        "on-secondary-fixed": "#241a00",
        "primary-fixed-dim": "#c9c6c5",
        "on-tertiary-container": "#dd4332",
        tertiary: "#ffb4a8",
        "surface-bright": "#393939",
        "secondary-fixed-dim": "#e9c349",
        primary: "#c9c6c5",
        outline: "#8e9192",
        "surface-container-lowest": "#0e0e0e",
        "surface-container": "#20201f",
        "on-background": "#e5e2e1",
        "surface-variant": "#353535",
        "tertiary-fixed-dim": "#ffb4a8",
        secondary: "#e9c349",
        "surface-container-high": "#2a2a2a",
        "surface-dim": "#131313",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#920703",
        "surface-container-highest": "#353535",
        surface: "#131313",
        "outline-variant": "#444748",
        error: "#ffb4ab",
        "on-tertiary-fixed": "#410000",
        "on-secondary-container": "#342800",
        "tertiary-container": "#250000",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "5rem",
        "section-gap": "8rem",
        "margin-mobile": "1.5rem",
        gutter: "1.5rem",
        "stack-unit": "0.5rem",
      },
      fontFamily: {
        "headline-xl": ["Playfair Display", "serif"],
        "label-caps": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "body-md": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "nav-link": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "nav-link": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
